# Welcome To Numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]], np.int32)

In [3]:
myarr[0,1]

np.int32(6)

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int32')

In [6]:
myarr[0,1] = 45

In [7]:
myarr

array([[ 3, 45, 32,  7]], dtype=int32)

# Array Creation : Conversion from other python structure

In [8]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [9]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [10]:
listarray.dtype

dtype('int64')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({32,32,23})

array({32, 23}, dtype=object)

In [14]:
zeros = np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
zeros.shape

(2, 5)

In [17]:
rng = np.arange(15)

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
linspace = np.linspace(1,4,4)

In [20]:
linspace

array([1., 2., 3., 4.])

In [21]:
emp = np.empty((4,6))

In [22]:
emp

array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307, 7.56587584e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.42417629e-306, 8.45593934e-307,
        6.89805151e-307, 1.60218491e-306, 6.89813978e-307],
       [6.89808546e-307, 1.37961506e-306, 2.22522597e-306,
        1.33511969e-306, 1.05695167e-307, 8.45610231e-307]])

In [23]:
emp_like = np.empty_like(linspace)
emp_like

array([1., 2., 3., 4.])

In [24]:
ide = np.identity(45)

In [25]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [26]:
ide.shape

(45, 45)

In [27]:
arr = np.arange(99)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr = arr.reshape(3,33)

In [30]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [31]:
arr= arr.ravel()

In [32]:
arr.shape

(99,)

In [33]:
x = [[1,2,3,],[4,5,6],[7,1,0]]

In [34]:
ar = np.array(x)

In [35]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [36]:
ar.sum(axis = 0 )

array([12,  8,  9])

In [37]:
ar.sum(axis = 1)

array([ 6, 15,  8])

In [38]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [39]:
ar.flat

In [40]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [41]:
ar.ndim

2

In [42]:
ar.size

9

In [43]:
ar.nbytes

72

In [46]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [47]:
ar2 = np.array([[1,2,1],
                [4,0,6],
                [8,1,0]])

In [48]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [49]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [50]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [51]:
ar.sum()

np.int64(29)

In [52]:
ar.max()

np.int64(7)

In [53]:
ar.min()

np.int64(0)

In [54]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [56]:
type(np.where(ar>5))

tuple

In [57]:
np.count_nonzero(ar)

8

In [58]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [59]:
ar[1,2]=0

In [60]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [61]:
import sys

In [63]:
py_ar= [ 0,4,55,2]

In [72]:
np_ar = np.array(py_ar)

In [76]:
sys.getsizeof(1) * len(py_ar)

112

In [74]:
np_ar.itemsize * np.ar.size

32

In [75]:
np_ar.tolist()

[0, 4, 55, 2]